error: consider errno as a return value
CGo provide us a way to get errno value from C code as a return value,
so it's always a good idea to make use of it.