install headers required for selftests
In file included from main.bpf.c:2:
In file included from ../../output/uapi/linux/bpf.h:11:
/usr/include/linux/types.h:5:10: fatal error: 'asm/types.h' file not
found